### PR TITLE
fix: Decrypt Android Keystore path errors

### LINKED ISSUE #28: Valid Namespace missing Alpha?
When running `encrypt_app_vars` it displays list of namespace (beat, release, ENTER = root) but it does not include alpha. When I input alpha it did get the correct `.env.alpha` file but could cause confusion to the user.

env alpha — lhc-mobile 2020-02-12 09-02-16

### PR DESCRIPTION
**Pull request by code-jenn-or**
Update decrypt keystore to optimize for CI and resolve errors in path, created issue 29 to follow-up and resolve directory/path issues for generating keystore from root directory on local machine.

Also add `alpha` namespace to the prompt when encrypting app_vars for issue #28

### CODE REVIEW

File: lib/fastlane/plugin/react_native_release/actions/decrypt_android_keystore.rb [hunk 1]
```diff
@@ -112,7 +120,7 @@ def self.details
 
       def self.authors
         # So no one will ever forget your contribution to fastlane :) You are awesome btw!
-        ["cball", "isaiahgrey93"]
+        ["cball", "isaiahgrey93", "cmejet"]
```
Comment (cball) [inline lib/fastlane/plugin/react_native_release/actions/decrypt_android_keystore.rb:123]: 🎉

**Review by cball — APPROVED** [review]
Looks good!
